# Analyze HealthPredictor Notebook Runs

In [1]:
# Standard Library:
from collections import defaultdict
import shelve

# 3rd Party:
from IPython.display import display as display
import pandas as pd

# Shelve Database:
DB = 'hp_results'

In [2]:
# Load the shelve database
with shelve.open(DB) as db:
    # Create a dictionary to group runs by model
    model_data = defaultdict(dict)

    for full_key, metrics in db.items():
        # Split into run and model
        run, model = full_key.split('/', 1)
        model_data[model][run] = metrics

# Now convert each model's runs into a DataFrame
model_dfs = {}

for model, runs in model_data.items():
    df = pd.DataFrame.from_dict(runs, orient='index')
    df.index.name = 'RUN#'
    model_dfs[model] = df

# Now model_dfs is a dictionary: model name -> corresponding DataFrame
for model in model_dfs:
    print(f'{model} model runs:\n{'=' * 100}')
    display(model_dfs[model])
    print(f'{model} model run statistics:\n{'=' * 100}')
    display(model_dfs[model].describe())

DecisionTreeClassifier model runs:
====================================================================================================

,accuracy,precision,recall,f1_score,misclassification,npv,fpr,specificity,prevalence,imputation
RUN#,,,,,,,,,,
0,0.983333,1.000000,0.972222,0.985915,0.016667,0.960000,0.000000,1.000000,0.6,random
1,0.950000,0.934211,0.986111,0.959459,0.050000,0.977273,0.104167,0.895833,0.6,random
2,0.950000,0.945946,0.972222,0.958904,0.050000,0.956522,0.083333,0.916667,0.6,random
3,0.933333,0.957143,0.930556,0.943662,0.066667,0.900000,0.062500,0.937500,0.6,random
4,0.983333,0.986111,0.986111,0.986111,0.016667,0.979167,0.020833,0.979167,0.6,random
5,0.975000,0.960000,1.000000,0.979592,0.025000,1.000000,0.062500,0.937500,0.6,random
6,0.950000,0.945946,0.972222,0.958904,0.050000,0.956522,0.083333,0.916667,0.6,random
7,0.925000,0.931507,0.944444,0.937931,0.075000,0.914894,0.104167,0.895833,0.6,random
8,0.958333,0.946667,0.986111,0.965986,0.041667,0.977778,0.083333,0.916667,0.6,random
9,0.958333,0.946667,0.986111,0.965986,0.041667,0.977778,0.083333,0.916667,0.6,random

DecisionTreeClassifier model run statistics:
====================================================================================================

,accuracy,precision,recall,f1_score,misclassification,npv,fpr,specificity,prevalence
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000e+01
mean,0.956667,0.955420,0.973611,0.964245,0.043333,0.959993,0.068750,0.931250,6.000000e-01
std,0.019563,0.021878,0.021165,0.016280,0.019563,0.030834,0.034091,0.034091,1.170278e-16
min,0.925000,0.931507,0.930556,0.937931,0.016667,0.900000,0.000000,0.895833,6.000000e-01
25%,0.950000,0.945946,0.972222,0.958904,0.029167,0.956522,0.062500,0.916667,6.000000e-01
50%,0.954167,0.946667,0.979167,0.962723,0.045833,0.968636,0.083333,0.916667,6.000000e-01
75%,0.970833,0.959286,0.986111,0.976190,0.050000,0.977778,0.083333,0.937500,6.000000e-01
max,0.983333,1.000000,1.000000,0.986111,0.075000,1.000000,0.104167,1.000000,6.000000e-01

DecisionTreeClassifier-GridSearchCV model runs:
====================================================================================================

,accuracy,precision,recall,f1_score,misclassification,npv,fpr,specificity,prevalence,imputation
RUN#,,,,,,,,,,
0,0.950000,1.000000,0.916667,0.956522,0.050000,0.888889,0.000000,1.000000,0.6,random
1,0.958333,0.958904,0.972222,0.965517,0.041667,0.957447,0.062500,0.937500,0.6,random
2,0.950000,0.945946,0.972222,0.958904,0.050000,0.956522,0.083333,0.916667,0.6,random
3,0.966667,0.947368,1.000000,0.972973,0.033333,1.000000,0.083333,0.916667,0.6,random
4,0.966667,0.959459,0.986111,0.972603,0.033333,0.978261,0.062500,0.937500,0.6,random
5,0.941667,0.957746,0.944444,0.951049,0.058333,0.918367,0.062500,0.937500,0.6,random
6,0.950000,0.958333,0.958333,0.958333,0.050000,0.937500,0.062500,0.937500,0.6,random
7,0.950000,0.923077,1.000000,0.960000,0.050000,1.000000,0.125000,0.875000,0.6,random
8,0.958333,0.958904,0.972222,0.965517,0.041667,0.957447,0.062500,0.937500,0.6,random
9,0.950000,0.934211,0.986111,0.959459,0.050000,0.977273,0.104167,0.895833,0.6,random

DecisionTreeClassifier-GridSearchCV model run statistics:
====================================================================================================

,accuracy,precision,recall,f1_score,misclassification,npv,fpr,specificity,prevalence
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000e+01
mean,0.954167,0.954395,0.970833,0.962088,0.045833,0.957171,0.070833,0.929167,6.000000e-01
std,0.008099,0.020226,0.025735,0.006999,0.008099,0.035076,0.032867,0.032867,1.170278e-16
min,0.941667,0.923077,0.916667,0.951049,0.033333,0.888889,0.000000,0.875000,6.000000e-01
25%,0.950000,0.946302,0.961806,0.958476,0.041667,0.942255,0.062500,0.916667,6.000000e-01
50%,0.950000,0.958040,0.972222,0.959730,0.050000,0.957447,0.062500,0.937500,6.000000e-01
75%,0.958333,0.958904,0.986111,0.965517,0.050000,0.978014,0.083333,0.937500,6.000000e-01
max,0.966667,1.000000,1.000000,0.972973,0.058333,1.000000,0.125000,1.000000,6.000000e-01

RandomForestClassifier model runs:
====================================================================================================

,accuracy,precision,recall,f1_score,misclassification,npv,fpr,specificity,prevalence,imputation
RUN#,,,,,,,,,,
0,0.991667,0.986301,1.0,0.993103,0.008333,1.0,0.020833,0.979167,0.6,random
1,0.983333,0.972973,1.0,0.986301,0.016667,1.0,0.041667,0.958333,0.6,random
2,0.958333,0.935065,1.0,0.966443,0.041667,1.0,0.104167,0.895833,0.6,random
3,0.975000,0.960000,1.0,0.979592,0.025000,1.0,0.062500,0.937500,0.6,random
4,0.983333,0.972973,1.0,0.986301,0.016667,1.0,0.041667,0.958333,0.6,random
5,0.983333,0.972973,1.0,0.986301,0.016667,1.0,0.041667,0.958333,0.6,random
6,0.975000,0.960000,1.0,0.979592,0.025000,1.0,0.062500,0.937500,0.6,random
7,0.975000,0.960000,1.0,0.979592,0.025000,1.0,0.062500,0.937500,0.6,random
8,0.958333,0.935065,1.0,0.966443,0.041667,1.0,0.104167,0.895833,0.6,random
9,0.958333,0.935065,1.0,0.966443,0.041667,1.0,0.104167,0.895833,0.6,random

RandomForestClassifier model run statistics:
====================================================================================================

,accuracy,precision,recall,f1_score,misclassification,npv,fpr,specificity,prevalence
count,10.000000,10.000000,10.0,10.000000,10.000000,10.0,10.000000,10.000000,1.000000e+01
mean,0.974167,0.959042,1.0,0.979011,0.025833,1.0,0.064583,0.935417,6.000000e-01
std,0.012076,0.018417,0.0,0.009620,0.012076,0.0,0.030190,0.030190,1.170278e-16
min,0.958333,0.935065,1.0,0.966443,0.008333,1.0,0.020833,0.895833,6.000000e-01
25%,0.962500,0.941299,1.0,0.969730,0.016667,1.0,0.041667,0.906250,6.000000e-01
50%,0.975000,0.960000,1.0,0.979592,0.025000,1.0,0.062500,0.937500,6.000000e-01
75%,0.983333,0.972973,1.0,0.986301,0.037500,1.0,0.093750,0.958333,6.000000e-01
max,0.991667,0.986301,1.0,0.993103,0.041667,1.0,0.104167,0.979167,6.000000e-01

XGBClassifier model runs:
====================================================================================================

,accuracy,precision,recall,f1_score,misclassification,npv,fpr,specificity,prevalence,imputation
RUN#,,,,,,,,,,
0,0.991667,0.986301,1.000000,0.993103,0.008333,1.000000,0.020833,0.979167,0.6,random
1,0.966667,0.947368,1.000000,0.972973,0.033333,1.000000,0.083333,0.916667,0.6,random
2,0.958333,0.946667,0.986111,0.965986,0.041667,0.977778,0.083333,0.916667,0.6,random
3,0.966667,0.959459,0.986111,0.972603,0.033333,0.978261,0.062500,0.937500,0.6,random
4,0.991667,0.986301,1.000000,0.993103,0.008333,1.000000,0.020833,0.979167,0.6,random
5,0.983333,0.972973,1.000000,0.986301,0.016667,1.000000,0.041667,0.958333,0.6,random
6,0.966667,0.947368,1.000000,0.972973,0.033333,1.000000,0.083333,0.916667,0.6,random
7,0.958333,0.935065,1.000000,0.966443,0.041667,1.000000,0.104167,0.895833,0.6,random
8,0.950000,0.945946,0.972222,0.958904,0.050000,0.956522,0.083333,0.916667,0.6,random
9,0.958333,0.946667,0.986111,0.965986,0.041667,0.977778,0.083333,0.916667,0.6,random

XGBClassifier model run statistics:
====================================================================================================

,accuracy,precision,recall,f1_score,misclassification,npv,fpr,specificity,prevalence
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000e+01
mean,0.969167,0.957412,0.993056,0.974838,0.030833,0.989034,0.066667,0.933333,6.000000e-01
std,0.014725,0.018194,0.009821,0.011980,0.014725,0.015449,0.029134,0.029134,1.170278e-16
min,0.950000,0.935065,0.972222,0.958904,0.008333,0.956522,0.020833,0.895833,6.000000e-01
25%,0.958333,0.946667,0.986111,0.966101,0.020833,0.977899,0.046875,0.916667,6.000000e-01
50%,0.966667,0.947368,1.000000,0.972788,0.033333,1.000000,0.083333,0.916667,6.000000e-01
75%,0.979167,0.969595,1.000000,0.982969,0.041667,1.000000,0.083333,0.953125,6.000000e-01
max,0.991667,0.986301,1.000000,0.993103,0.050000,1.000000,0.104167,0.979167,6.000000e-01

LogisticRegression model runs:
====================================================================================================

,accuracy,precision,recall,f1_score,misclassification,npv,fpr,specificity,prevalence,imputation
RUN#,,,,,,,,,,
0,0.941667,0.957746,0.944444,0.951049,0.058333,0.918367,0.062500,0.937500,0.6,random
1,0.941667,0.945205,0.958333,0.951724,0.058333,0.936170,0.083333,0.916667,0.6,random
2,0.950000,0.958333,0.958333,0.958333,0.050000,0.937500,0.062500,0.937500,0.6,random
3,0.975000,1.000000,0.958333,0.978723,0.025000,0.941176,0.000000,1.000000,0.6,random
4,0.975000,1.000000,0.958333,0.978723,0.025000,0.941176,0.000000,1.000000,0.6,random
5,0.958333,0.985507,0.944444,0.964539,0.041667,0.921569,0.020833,0.979167,0.6,random
6,0.958333,0.971831,0.958333,0.965035,0.041667,0.938776,0.041667,0.958333,0.6,random
7,0.950000,0.958333,0.958333,0.958333,0.050000,0.937500,0.062500,0.937500,0.6,random
8,0.950000,0.958333,0.958333,0.958333,0.050000,0.937500,0.062500,0.937500,0.6,random
9,0.966667,0.985714,0.958333,0.971831,0.033333,0.940000,0.020833,0.979167,0.6,random

LogisticRegression model run statistics:
====================================================================================================

,accuracy,precision,recall,f1_score,misclassification,npv,fpr,specificity,prevalence
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000e+01
mean,0.956667,0.972100,0.955556,0.963662,0.043333,0.934973,0.041667,0.958333,6.000000e-01
std,0.012298,0.019493,0.005856,0.010055,0.012298,0.008115,0.029463,0.029463,1.170278e-16
min,0.941667,0.945205,0.944444,0.951049,0.025000,0.918367,0.000000,0.916667,6.000000e-01
25%,0.950000,0.958333,0.958333,0.958333,0.035417,0.936503,0.020833,0.937500,6.000000e-01
50%,0.954167,0.965082,0.958333,0.961436,0.045833,0.937500,0.052083,0.947917,6.000000e-01
75%,0.964583,0.985663,0.958333,0.970132,0.050000,0.939694,0.062500,0.979167,6.000000e-01
max,0.975000,1.000000,0.958333,0.978723,0.058333,0.941176,0.083333,1.000000,6.000000e-01